### ISSUE TITLE
[UI] Make our app screen vertically scrollable 

### ISSUE THREAD

**Issue by Shaomei** [aimpowered/LibOrate#103]
The screen is currently non-scrollable vertically, as a result, bottom part of the content will be out of reach when the screen is shorter than expected. 

We need to make the screen vertically scrollable to allow user to see and interact with all components of the app.

**Comment by jdzhrch** [comment]
![Screenshot2024_12_10_30222 PM](https://github.com/user-attachments/assets/fed94cd7-b068-48e7-af40-6aee33dbdbbe)
