### ISSUE TITLE
[UI/DB] Remove username field from sign up flow

### ISSUE THREAD

**Issue by Shaomei** [aimpowered/LibOrate#93]
There is currently a mismatches between login and sign up information. The sign up page asks username and email while users can only sign in via email. The consistency issues needs to be fixed by removing the username field in the sign up page and just use emails for log in. Remember to make sure the username field is removed and not used in later DB operations as well.

**Sign up page:**
<img width="362" alt="image" src="https://github.com/user-attachments/assets/525ce017-be2b-40ea-94ca-3273f1ef5896">

**Login page:**
<img width="366" alt="image (1)" src="https://github.com/user-attachments/assets/9269769b-fc17-4f57-8d95-ec314b5f7025">

**Comment by rrahul32** [comment]
Hi, I would like to contribute. Can you assign me this issue?

**Comment by charansr** [comment]
I implemented the username removal and wrote the unit tests for the signup page to check that the username was removed. I pushed the changes to the username_removal branch.

**Comment by charansr** [comment]
Here is a screenshot of the signup page without the username field. 
<img width="673" alt="username_removal_ss" src="https://github.com/user-attachments/assets/247a8319-1355-4397-8b58-f455c48abb56">
